/*
 Controller v0.2.1 | (c) 2024 Nerijus Jasinskas */
(function(){function u(){var a=jQuery("a").not("#p a");a.off("click");a.click(function(c){v(c)})}function B(a,c){function b(e){$(e).delay(400).animate({C:90},{step:function(g){$(this).css("transform","rotate("+(g-90)+"deg)")}},{duration:750,queue:!1})}function f(e=500){function g(k){k=Math.min((k-l)/e,1);window.scrollTo(0,m*(1-k));k<1&&requestAnimationFrame(g)}const m=window.scrollY,l=performance.now();requestAnimationFrame(g)}var d=jQuery("#c");d.fadeOut(300,function(){C(a.split(".").slice(-0)[0]);
window.dispatchEvent(new CustomEvent("e"));jQuery.fx.off=0;d.html(c);location.hash=a;if(!w.A(a)){y();x(a);f();b(".section-subtitle, .di p, .di :header:not(h1), .di ul, .di .anim");u();for(var e=document.querySelectorAll("h1"),g=0;g<e.length;g++)for(var m=e[g].childNodes,l=0;l<m.length;l++){var k=m[l];k.nodeType===3&&k.textContent.trim().length>0&&k.parentNode.replaceChild(z(k.textContent),k)}}})}function C(a){jQuery("nav").find("a").each(function(){var c=jQuery(this);
c.attr("href").indexOf(a)>=0?c.addClass("ce"):c.removeClass("ce")})}function D(){function a(){var d=Math.round(b/c*100);b++;d<100?setTimeout(a,f):(d=100,jQuery("#pb").fadeOut());jQuery("#pb").width(d+"%")}var c=100,b=1,f=50;jQuery("#pb").show();this.o=function(){f=1;c=10};a()}function t(a,c,b,f,d){this.l=a;this.m=c;this.g=b;this.j=f;this.v=d}function A(a,c){for(var b in h)a==n.h&&h[b].g==c&&(h[b].j=!0),a==n.i&&(h[b].m=h[b].l==c),h[b].m==1&&h[b].j==1&&window.dispatchEvent(new CustomEvent("b",
{detail:{id:h[b].g}}))}function x(a,c){setTimeout(()=>{p=!1},10);a=a.split("/").slice(-1)[0];a.length&&a.indexOf("#")!=0||(a="index.html"+a);var b=a.split("#").slice(-0)[0],f=a.split("#").slice(-1)[0];var d=b.split(".").slice(-0)[0];var e=f.split(".").slice(-0)[0];q!==e&&(w.u(e)||(void 0!==c?v(null,f):b!==f&&q!==e?v(null,f):(p=!1,q=d,jQuery(document).trigger(n.i,[d]),E(a))),w.B(e))}function z(a){var c=document.createDocumentFragment();const b=Math.min(window.innerWidth*.1,200);for(var f=0;f<a.length;f++){var d=
a.charAt(f),e=document.createElement("span");e.className="m5";e.textContent=d===" "?"\u00a0":d;e.style.setProperty("--rx",Math.random()*b-b/2+"px");e.style.setProperty("--ry",Math.random()*b-b/2+"px");c.appendChild(e)}return c}function y(){document.getElementById("c").style.display="block";document.getElementById("c").style.opacity="1"}function E(a){for(var c in h)if(a.indexOf(h[c].l)>=0&&!h[c].j){(function(b){Common.getScript("../js/"+h[b].g+".js?v=49",function(){h[b].v?Common.getScript("../js/"+
h[b].v+".min.js?v=3",function(){jQuery(document).trigger(n.h,h[b].g)}):jQuery(document).trigger(n.h,h[b].g)})})(c);break}}function v(a,c){if(!p){var b=void 0!=a?jQuery(a.currentTarget).attr("href"):c;if(b.length&&!(b.indexOf("html")<0)&&(void 0!=a&&a.preventDefault(),!b.includes(q))){p=!0;var f=new D;jQuery.ajax({url:b.lastIndexOf("/")>=0?b.replace("/de/","/de/part/"):"part/"+b,dataType:"html"}).done(function(d){p=!1;f.o();B(b,d);(function(){typeof dataLayer!=="undefined"&&dataLayer.push(arguments)})("event",
"page_view",{page_location:b})}).error(function(){p=!1;f.o()})}}}function r(a,c){if(a){var b=!1;a.style.transition="opacity 1000ms";c===1?(window.getComputedStyle(a).display==="none"&&(a.style.display=""),setTimeout(()=>{a.style.opacity="1"},10)):a.style.opacity="0";var f=()=>{b||(b=!0,c===0&&(a.style.display="none"))};a.addEventListener("transitionend",f,{once:!0});setTimeout(f,1050)}}var n={h:"j",i:"d"},q="none",p=!1,w=new function(){function a(d){const e=document.getElementById("i");e&&(e.style.pointerEvents=
d.includes("index")?"auto":"none")}function c(d){if(d.includes("index")){if(document.querySelectorAll(".gd").length===0&&(d=document.querySelectorAll("#i2 li"),d.length>0)){let g=document.createElement("a");g.href="service.html";document.getElementById("c").append(g);for(let m=0;m<d.length;m++){const l=document.createElement("div");g.appendChild(l);l.classList.add("gd");l.style.display=m===0?"":"none";l.replaceChildren(z(d[m].textContent))}u()}var e=document.querySelectorAll(".gd");
if(e.length>0){let g=0;f&&clearInterval(f);f=setInterval(()=>{r(e[g],0);g=(g+1)%e.length;r(e[g],1)},5E3)}}}var b=!1;let f=null;this.B=function(d){a(d);b!==!0&&(r(document.getElementById("i2"),0),c(d),Common.getScript("../js/three.mod.min.js",function(){b=!0;new window.In2;r(document.querySelector("#i > canvas"),1)}))};this.u=function(d){return b&&d.includes("index")};this.A=function(d){a(d);return this.u(d)?(q="index",r(document.getElementById("i2"),0),c(d),y(),!0):!1}},h=[new t("index",0,"",1,null),
new t("industries",0,"sph",0,null),new t("profile",0,"srch",0,"d3"),new t("contact",0,"ct",0,null)];jQuery(document).on(n.h,function(a,c){A(n.h,c)});jQuery(document).on(n.i,function(a,c){A(n.i,c)});jQuery(window).on("hashchange",function(){x(location.href,!0)});Common.getScript("../js/gdpr.js?v=1");document.title="Nerijus Jasinskas Software Engineering";u();x(location.href);document.getElementById("cy").innerHTML=(new Date).getFullYear()})();
