/*
 Controller v0.2.1 | (c) 2024 Nerijus Jasinskas */
(function(){function r(){var a=jQuery("a").not("#p a");a.off("click");a.click(function(a){k(a)})}function v(a,e){function b(){$(".qs :header, .qk p, .qk li, .qk .an").animate({k:90},{step:function(a){$(this).css("transform","rotate("+(a-90)+"deg)")}},{duration:75750,queue:!1})}var d=jQuery("#c");d.fadeOut(300,function(){w(a.split(".").slice(-0)[0]);jQuery(document).trigger(g.j);jQuery.fx.off=0;d.html(e);d.fadeTo(0,0,function(){location.hash=a;l(a);d.animate({padding:"30px 0 0 10px",
opacity:"1.0"},500);d.animate({padding:0},250);$("html").animate({scrollTop:0},{duration:500,queue:!1});b();r()})});for(var c=document.querySelectorAll("h1"),h=0;h<c.length;h++)(function(a){function b(a){a=a.childNodes;for(var e=0;e<a.length;e++){var d=a[e];if(3===d.nodeType&&0<d.textContent.trim().length){for(var c=d.textContent,g=document.createDocumentFragment(),m=0;m<c.length;m++){var h=c.charAt(m),f=document.createElement("span");f.className="mi";f.textContent=" "===h?"\u00a0":h;f.style.setProperty("--rx",
200*Math.random()-100+"px");f.style.setProperty("--ry",200*Math.random()-100+"px");g.appendChild(f)}d.parentNode.replaceChild(g,d)}else 1===d.nodeType&&b(d)}}b(a)})(c[h])}function w(a){jQuery(".u6").find("a").each(function(){var e=jQuery(this);0<=e.attr("href").indexOf(a)?e.addClass("ah"):e.removeClass("ah")})}function x(){function a(){var c=Math.round(b/e*100);b++;100>c?setTimeout(a,d):(c=100,jQuery("#pb").fadeOut());jQuery("#pb").width(c+"%")}var e=100,b=1,d=50;jQuery("#pb").show();this.f=
function(){d=1;e=10};a()}function n(a,e,b){this.g=a;this.h=0;this.a=e;this.b=0;this.e=b}function s(a,e){for(var b in f)a==g.c&&f[b].a==e&&(f[b].b=!0);for(b in c)if(a==g.c&&c[b].a==e&&(c[b].b=!0),a==g.d&&(c[b].h=c[b].g==e),!0==c[b].h&&!0==c[b].b){if(c[b].e){var d=t(f,c[b].e);if(d&&!d.b)break}jQuery(document).trigger(g.i,[c[b].a])}}function l(a,e){var b,d;a=a.split("/").slice(-1)[0];a.length&&0!=a.indexOf("#")||(a="index.html"+a);var c=a.split("#").slice(-0)[0],f=a.split("#").slice(-1)[0];b=c.split(".").slice(-0)[0];
d=f.split(".").slice(-0)[0];void 0!=e?q!=d&&k(null,f):(q=b,c!=f&&q!=d?k(null,f):(jQuery(document).trigger(g.d,[b]),u(a)))}function u(a){for(p in c)if(0<=a.indexOf(c[p].g)&&!c[p].b){Common.getScript("../js/"+c[p].a+".js?v=48");c[p].e&&(a=t(f,c[p].e))&&!a.b&&Common.getScript("../js/"+a.a+".min.js?v=3",function(a){if(a==f[0].a)var b=0,c=window.setInterval(function(){b||void 0==window.d3||(b=1,window.clearInterval(c),jQuery(document).trigger(g.c,[a]))},50);else jQuery(document).trigger(g.c,[a])}(a.a));
break}}function t(a,c){for(p in a){var b=a[p];if(c==b.a)return b}}function k(a,c){var b=void 0!=a?jQuery(a.currentTarget).attr("href"):c;if(b.length&&!(0>b.indexOf("html"))){void 0!=a&&a.preventDefault();u(b);var d=new x;jQuery.ajax({url:0<=b.lastIndexOf("/")?b.replace("/de/","/de/part/"):"part/"+b,dataType:"html"}).done(function(a){d.f();v(b,a);(function(){dataLayer.push(arguments)})("event","page_view",{page_location:b})}).error(function(){d.f()})}}var g={c:"j",d:"d",i:"b",j:"e"},q="",c=[new n("index",
"intr",null),new n("industries","sph",null),new n("profile","srch","d3")],f=[new function(a,c){this.a=a;this.b=c}("d3",0)];jQuery(document).on(g.c,function(a,c){s(g.c,c)});jQuery(document).on(g.d,function(a,c){s(g.d,c)});jQuery(window).on("hashchange",function(){l(location.href,!0)});Common.getScript("../js/gdpr.js?v=1");document.title="Nerijus Jasinskas Software Engineering";r();l(location.href);document.getElementById("cy").innerHTML=(new Date).getFullYear()})();
