/*
 Controller v0.2.1 | (c) 2024 Nerijus Jasinskas */
(function(){function r(){var a=jQuery("a").not("#p a");a.off("click");a.click(function(a){k(a)})}function v(a,d){function b(){$(".qs :header, .qk p, .qk li, .qk .an").animate({k:90},{step:function(a){$(this).css("transform","rotate("+(a-90)+"deg)")}},{duration:75750,queue:!1})}var e=jQuery("#c");e.fadeOut(300,function(){w(a.split(".").slice(-0)[0]);jQuery(document).trigger(f.j);jQuery.fx.off=0;e.html(d);e.fadeTo(0,0,function(){location.hash=a;m(a);e.animate({padding:"30px 0 0 10px",
opacity:"1.0"},500);e.animate({padding:0},250);$("html").animate({scrollTop:0},{duration:500,queue:!1});b();r();for(var d=document.querySelectorAll("h1"),c=0;c<d.length;c++)(function(a){function b(a){a=a.childNodes;for(var d=0;d<a.length;d++){var e=a[d];if(3===e.nodeType&&0<e.textContent.trim().length){for(var c=e.textContent,f=document.createDocumentFragment(),l=0;l<c.length;l++){var g=c.charAt(l),h=document.createElement("span");h.className="mi";h.textContent=" "===g?"\u00a0":g;h.style.setProperty("--rx",
200*Math.random()-100+"px");h.style.setProperty("--ry",200*Math.random()-100+"px");f.appendChild(h)}e.parentNode.replaceChild(f,e)}else 1===e.nodeType&&b(e)}}b(a)})(d[c])})})}function w(a){jQuery(".u6").find("a").each(function(){var d=jQuery(this);0<=d.attr("href").indexOf(a)?d.addClass("ah"):d.removeClass("ah")})}function x(){function a(){var c=Math.round(b/d*100);b++;100>c?setTimeout(a,e):(c=100,jQuery("#pb").fadeOut());jQuery("#pb").width(c+"%")}var d=100,b=1,e=50;jQuery("#pb").show();
this.f=function(){e=1;d=10};a()}function n(a,d,b){this.g=a;this.h=0;this.a=d;this.b=0;this.e=b}function s(a,d){for(var b in g)a==f.c&&g[b].a==d&&(g[b].b=!0);for(b in c)if(a==f.c&&c[b].a==d&&(c[b].b=!0),a==f.d&&(c[b].h=c[b].g==d),!0==c[b].h&&!0==c[b].b){if(c[b].e){var e=t(g,c[b].e);if(e&&!e.b)break}jQuery(document).trigger(f.i,[c[b].a])}}function m(a,d){var b,e;a=a.split("/").slice(-1)[0];a.length&&0!=a.indexOf("#")||(a="index.html"+a);var c=a.split("#").slice(-0)[0],g=a.split("#").slice(-1)[0];b=
c.split(".").slice(-0)[0];e=g.split(".").slice(-0)[0];void 0!=d?q!=e&&k(null,g):(q=b,c!=g&&q!=e?k(null,g):(jQuery(document).trigger(f.d,[b]),u(a)))}function u(a){for(p in c)if(0<=a.indexOf(c[p].g)&&!c[p].b){Common.getScript("../js/"+c[p].a+".js?v=48");c[p].e&&(a=t(g,c[p].e))&&!a.b&&Common.getScript("../js/"+a.a+".min.js?v=3",function(a){if(a==g[0].a)var b=0,c=window.setInterval(function(){b||void 0==window.d3||(b=1,window.clearInterval(c),jQuery(document).trigger(f.c,[a]))},50);else jQuery(document).trigger(f.c,
[a])}(a.a));break}}function t(a,d){for(p in a){var b=a[p];if(d==b.a)return b}}function k(a,d){var b=void 0!=a?jQuery(a.currentTarget).attr("href"):d;if(b.length&&!(0>b.indexOf("html"))){void 0!=a&&a.preventDefault();u(b);var c=new x;jQuery.ajax({url:0<=b.lastIndexOf("/")?b.replace("/de/","/de/part/"):"part/"+b,dataType:"html"}).done(function(a){c.f();v(b,a);(function(){dataLayer.push(arguments)})("event","page_view",{page_location:b})}).error(function(){c.f()})}}var f={c:"j",d:"d",i:"b",j:"e"},q=
"",c=[new n("index","intr",null),new n("industries","sph",null),new n("profile","srch","d3")],g=[new function(a,c){this.a=a;this.b=c}("d3",0)];jQuery(document).on(f.c,function(a,c){s(f.c,c)});jQuery(document).on(f.d,function(a,c){s(f.d,c)});jQuery(window).on("hashchange",function(){m(location.href,!0)});Common.getScript("../js/gdpr.js?v=1");document.title="Nerijus Jasinskas Software Engineering";r();m(location.href);document.getElementById("cy").innerHTML=(new Date).getFullYear()})();
