/*
 Controller v0.2.1 | (c) 2024 Nerijus Jasinskas */
(function(){function x(a,c){function b(a){window.scrollTo(0,0);a.style.padding="30px 0 0 10px";a.style.transition="padding 400ms, opacity 1000ms";a.style.opacity=1;setTimeout(function(){a.style.padding="0px"},400)}function d(){for(var a=document.querySelectorAll("h1"),b=0;b<a.length;b++)(function(a){function b(a){a=a.childNodes;for(var c=0;c<a.length;c++){var d=a[c];if(3===d.nodeType&&0<d.textContent.trim().length){for(var e=d.textContent,f=document.createDocumentFragment(),g=0;g<e.length;g++){var h=
e.charAt(g),l=document.createElement("span");l.className="ro";l.textContent=" "===h?"\u00a0":h;l.style.setProperty("--rx",200*Math.random()-100+"px");l.style.setProperty("--ry",200*Math.random()-100+"px");f.appendChild(l)}d.parentNode.replaceChild(f,d)}else 1===d.nodeType&&b(d)}}b(a)})(a[b])}var e=document.getElementById("c");(function(a,b,c){a.style.opacity=0;a.style.transition="opacity "+b+"ms";setTimeout(function(){c()},b)})(e,300,function(){var g=a.split(".").slice(-0)[0],f=document.querySelector(".u6");
if(f)for(var f=f.getElementsByTagName("a"),k=0;k<f.length;k++)0<=(f[k].getAttribute("href")||"").indexOf(g)?f[k].classList.add("ah"):f[k].classList.remove("ah");m(h.j);e.innerHTML=c;location.hash=a;n(a);g=document.querySelectorAll(".qk p, .qk li, .qk .an");for(f=0;f<g.length;f++)g[f].style.transform="rotate(-90deg)",g[f].offsetWidth,g[f].style.transition="transform 650ms linear",g[f].style.transform="rotate(0deg)";t();d();b(e)})}function y(){function a(){var e=Math.round(b/
c*100);b++;100>e?setTimeout(a,d):(e=100,jQuery("#pb").fadeOut());jQuery("#pb").width(e+"%")}var c=100,b=1,d=50;jQuery("#pb").show();this.f=function(){d=1;c=10};a()}function q(a,c,b){this.g=a;this.h=0;this.a=c;this.b=0;this.e=b}function m(a,c){var b=document.createEvent("Event");b.initEvent(a,!0,!0);b.detail=c;document.dispatchEvent(b)}function u(a,c){for(var b in k)a===h.c&&k[b].a===c&&(k[b].b=!0);for(b in e)if(a===h.c&&e[b].a===c&&(e[b].b=!0),a===h.d&&(e[b].h=e[b].g===c),!0===e[b].h&&!0===e[b].b){if(e[b].e){var d=
v(k,e[b].e);if(d&&!d.b)break}m(h.i,e[b].a)}}function n(a,c){var b,d;a=a.split("/").slice(-1)[0];a.length&&0!=a.indexOf("#")||(a="index.html"+a);var e=a.split("#").slice(-0)[0],g=a.split("#").slice(-1)[0];b=e.split(".").slice(-0)[0];d=g.split(".").slice(-0)[0];void 0!=c?r!=d&&s(null,g):(r=b,e!=g&&r!=d?s(null,g):(m(h.d,b),w(a)))}function w(a){for(p in e)if(0<=a.indexOf(e[p].g)&&!e[p].b){Common.getScript("../js/"+e[p].a+".js?v=48");e[p].e&&(a=v(k,e[p].e))&&!a.b&&Common.getScript("../js/"+a.a+".min.js?v=3",
function(a){if(a==k[0].a)var b=0,d=window.setInterval(function(){b||void 0==window.d3||(b=1,window.clearInterval(d),jQuery(document).trigger(h.c,[a]))},50);else jQuery(document).trigger(h.c,[a])}(a.a));break}}function v(a,c){for(p in a){var b=a[p];if(c==b.a)return b}}function z(a,c,b){var d=new XMLHttpRequest;d.open("GET",a,!0);d.onreadystatechange=function(){4===d.readyState&&(200===d.status?c(d.responseText):b&&b())};d.send()}function s(a,c){var b=a?a.currentTarget.getAttribute("href"):c;if(b&&
!(0>b.indexOf("html"))){a&&a.preventDefault();w(b);var d=new y;z(0<=b.lastIndexOf("/")?b.replace("/de/","/de/part/"):"part/"+b,function(a){d.f();x(b,a);(function(){"undefined"!==typeof dataLayer&&dataLayer.push(arguments)})("event","page_view",{page_location:b})},function(){d.f()})}}function t(){for(var a=document.getElementsByTagName("a"),c=0;c<a.length;c++)a[c].closest("#p")||(a[c].onclick=function(a){s(a)})}var h={c:"j",d:"d",i:"b",j:"e"},r="",e=[new q("index","intr",null),new q("industries","sph",
null),new q("profile","srch","d3")],k=[new function(a,c){this.a=a;this.b=c}("d3",0)];jQuery(document).on(h.c,function(a,c){u(h.c,c)});jQuery(document).on(h.d,function(a,c){u(h.d,c)});jQuery(window).on("hashchange",function(){n(location.href,!0)});Common.getScript("../js/gdpr.js?v=1");document.title="Nerijus Jasinskas Software Engineering";t();n(location.href);document.getElementById("cy").innerHTML=(new Date).getFullYear()})();
