/*
 Slider v0.2.0 | (c) 2014 Nerijus Jasinskas */
(function(){function A(){function p(a){a=a.c;return'<div id="f'+a+'"><div id="ff'+a+'" class="qs x8"><div id="i'+a+'"><canvas id="k'+a+'" width="'+v+'" height="'+y+'"></canvas></div><div id="b'+a+'" class="x8 u5"></div><div id="h'+a+'" class="x8"><h1>'+s[a]+"</h1></div></div></div>"}function n(a){a=a.c;return'<a name="'+a+'" href=""><div id="n'+a+'" class="vz" style="left:'+(v-10-20*(l.length-a))+'px"><div id="ib'+a+'" class="yf"></div></div></a>'}
var c=this,q=null,d=0,r=(new Date).getTime()+"-"+Math.floor(1E3*Math.random()+1),t=0;this.e=function(){return r};var k=[],w=!0,v=780,y=300,s=[],l=[];if(0<=navigator.userAgent.indexOf("MSIE 6")||0<=navigator.userAgent.indexOf("MSIE 7")||0<=navigator.userAgent.indexOf("MSIE 8"))w=!1;this.l=function(){var a=document.getElementById("t");if(null!=a)for(var a=a.getElementsByTagName("a"),b=0;b<a.length;++b)s.push(a[b].innerHTML),l.push(a[b].href)};this.o=function(a){function b(){var b=x[0];if(!b.d){var c=
new Image;b.image=c;b.loaded=!1;c.onload=function(){b.loaded=!0;var g,e=c.width,h=c.height,d=p/r;g=h*d;var f=h;g>e&&(g=e,f=e/d);e=(e-g)/2;h=(h-f)/2;g=[e,h,e+g,h+f];f=(g[2]+g[0])/2;h=(g[3]+g[1])/2;e=(g[2]-g[0])*z;d=(g[3]-g[1])*z;f=[f-e/2,h-d/2,f+e/2,h+d/2];e=Math.floor(3*Math.random())-1;h=Math.floor(3*Math.random())-1;e/=2;h/=2;d=f[0];f[0]+=d*e;f[2]+=d*e;e=f[1];f[1]+=e*h;f[3]+=e*h;Math.floor(10*Math.random())%2?(b.i=g,b.j=f):(b.i=f,b.j=g);a.u&&a.u(k)};b.d=!0;c.src=b.path}return b}function c(){var n=
(new Date).getTime()-l,m=n/q;if(!(1<m)){var g=b();if(g.loaded){var e=g.i,h=g.j,u=e[0],f=e[1],v=e[2],e=e[3],m=[u+(h[0]-u)*m,f+(h[1]-f)*m,v+(h[2]-v)*m,e+(h[3]-e)*m];d.save();d.globalAlpha=1;d.drawImage(g.image,m[0],m[1],m[2]-m[0],m[3]-m[1],0,0,p,r);d.restore()}}0<t&&!1==s&&q-n<=t&&(a.t&&a.t(k,q-n),s=!0);n>=q&&k.stop()}if(!w)return null;var d=jQuery("#"+a.name)[0].getContext("2d"),k=this,l=0,p=v,r=y,q=a.w||9E3,t=a.A||0,s=!1,n=1/(a.B||30)*1E3,z=1/(a.zoom||1.5),u=null,x=[];x.push({path:a.image,d:!1,loaded:!1});
this.stop=function(){null!=u&&clearInterval(u);u=null;x[0].d=null;a.v&&a.v(k)};this.start=function(){s=!1;l=0;l=(new Date).getTime()-l;u=setInterval(c,n)};b();return this};this.a=function(a,b){0==b?jQuery("#ib"+a).removeClass("xx"):jQuery("#ib"+a).addClass("xx")};this.h=function(){null!=q&&(window.clearTimeout(q),q=null)};this.m=function(){var a=d;a++;a==l.length&&(a=0);return a};this.b=function(){for(var a=0;a<l.length;a++)jQuery("#f"+a).stop(!0,!0),jQuery("#ff"+a).stop(!0,!0)};this.k=function(){c.h();
for(var a=0;a<k.length;a++)k[a].stop();this.b()};this.r=function(){var a=d;d=c.m();c.g(a,d)};this.s=function(a){if(1==t||d==a){if(d==a)return;c.b()}var b=d;d=a;c.g(b,d)};this.g=function(a,b){1==t&&c.b();t=1;c.f();k.length>b&&k[b].start();jQuery("#ff"+a).css("z-index",1);jQuery("#ff"+b).css("z-index",2);jQuery("#ff"+b).hide().fadeIn(2500,function(){if(r!=c.e())return!1;jQuery("#f"+a).hide();t=0});c.a(a,0);c.a(b,1);jQuery("#f"+b).show(1,function(){});k.length>a&&k[a].stop()};this.f=function(){c.h();
null!=document.getElementById("p")&&(q=window.setTimeout(function(){null!=c&&c.p(r)},5E3))};this.p=function(a){r==a&&c.r()};this.n=function(){d=0;c.f();k.length&&k[0].start();jQuery("#f"+d).show(1,function(){if(r!=c.e())return!1;c.a(d,1)})};this.q=function(){if(null!=document.getElementById("p")){this.l();for(var a='<div style="position: relative;">',b=0;b<s.length;b++)a+=p({c:b});for(b=0;b<l.length;b++)a+=n({c:b});a+="</div>";jQuery("#p").html(a);jQuery("#p a").bind("click",function(){if(0<this.name.length&&
!1==isNaN(this.name))return c.s(parseInt(this.name)),!1});for(b=0;b<l.length;b++)!0==w?k[b]=new c.o({name:"k"+b,image:l[b]}):jQuery("#i"+b).html('<img src="'+l[b]+'" />'),jQuery("#f"+b).hide();c.n()}};c.q()}var p;jQuery(document).on("e",function(){null!=p&&p.k();jQuery.fx.off=1;p=null});jQuery(document).on("b",function(B,n){p||"intr"!=n||(p=new A)});jQuery(document).trigger("j",["intr"])})();
