/* Slider v0.2.0 | (c) 2014 Nerijus Jasinskas */
(function(){function J(){var f=this,u=null,q=0,r=(new Date).getTime()+"-"+Math.floor(Math.random()*1E3+1),A=0;this.i=function(){return r};var n=[],B=!0,C=[],p=[];if(navigator.userAgent.indexOf("MSIE 6")>=0||navigator.userAgent.indexOf("MSIE 7")>=0||navigator.userAgent.indexOf("MSIE 8")>=0)B=!1;this.C=function(){var a=document.getElementById("t");if(a!=null){a=a.getElementsByTagName("a");for(var b=0;b<a.length;++b)C.push(a[b].innerHTML),p.push(a[b].href)}};this.o=function(a){function b(){var h=D[0];
if(!h.h){var k=new Image;h.image=k;h.loaded=!1;k.onload=function(){h.loaded=!0;var e=k.width,g=k.height,l=915/365;var c=g*l;var d=g;c>e&&(c=e,d=e/l);e=(e-c)/2;g=(g-d)/2;c=[e,g,e+c,g+d];d=(c[2]+c[0])/2;g=(c[3]+c[1])/2;e=(c[2]-c[0])*F;l=(c[3]-c[1])*F;d=[d-e/2,g-l/2,d+e/2,g+l/2];e=Math.floor(Math.random()*3)-1;g=Math.floor(Math.random()*3)-1;e/=2;g/=2;l=d[0];d[0]+=l*e;d[2]+=l*e;e=d[1];d[1]+=e*g;d[3]+=e*g;Math.floor(Math.random()*10)%2?(h.r1=c,h.r2=d):(h.r1=d,h.r2=c);if(a.onloaded)a.onloaded(v)};h.h=
!0;k.src=h.path}return h}function m(){var h=(new Date).getTime()-w;var k=h/x;if(!(k>1)){var e=b();if(e.loaded){var g=e.r1;var l=e.r2;var c=g[0];var d=g[1];c+=(l[0]-c)*k;d+=(l[1]-d)*k;var G=g[2],H=g[3];g=G+(l[2]-G)*k;k=H+(l[3]-H)*k;c=[c,d,g,k];y.save();y.globalAlpha=1;y.drawImage(e.image,c[0],c[1],c[2]-c[0],c[3]-c[1],0,0,915,365);y.restore()}}I>0&&E==0&&x-h<=I&&(a.F&&a.F(v,x-h),E=!0);h>=x&&v.stop()}if(!B)return null;var y=jQuery("#"+a.name)[0].getContext("2d"),v=this,w=0,x=a.I||9E3,I=a.J||0,E=!1,K=
1/(a.K||30)*1E3,F=1/(a.zoom||1.5),z=null,D=[];D.push({path:a.image,h:!1,loaded:!1});this.stop=function(){z!=null&&clearInterval(z);z=null;D[0].h=null;if(a.onstop)a.onstop(v)};this.start=function(){E=!1;w=0;w=(new Date).getTime()-w;z=setInterval(m,K)};b();return this};this.g=function(a,b){b==0?jQuery("#n"+a).removeClass("r8"):jQuery("#n"+a).addClass("r8")};this.m=function(){u!=null&&(window.clearTimeout(u),u=null)};this.G=function(){var a=q;a++;a==p.length&&(a=0);return a};this.l=function(){for(var a=
0;a<p.length;a++)jQuery("#f"+a).stop(!0,!0),jQuery("#ff"+a).stop(!0,!0)};this.D=function(){f.m();for(var a=0;a<n.length;a++)n[a].stop();this.l()};this.A=function(){var a=q;q=f.G();f.B(a,q)};this.B=function(a,b){A==1&&f.l();A=1;f.j();n.length>b&&n[b].start();jQuery("#ff"+a).css("z-index",1);jQuery("#ff"+b).css("z-index",2);jQuery("#ff"+b).hide().fadeIn(2500,function(){if(r!=f.i())return!1;jQuery("#f"+a).hide();A=0});f.g(a,0);f.g(b,1);jQuery("#f"+b).show(1,function(){});n.length>a&&n[a].stop()};this.j=
function(){f.m();document.getElementById("p")!=null&&(u=window.setTimeout(function(){f!=null&&f.u(r)},5E3))};this.u=function(a){r==a&&f.A()};this.H=function(){q=0;f.j();n.length&&n[0].start();jQuery("#f"+q).show(1,function(){if(r!=f.i())return!1;f.g(q,1)})};this.v=function(){if(document.getElementById("p")!=null){this.C();for(var a='<div style="position: relative;">',b=0;b<C.length;b++){var m=b;a+='<div id="f'+m+'"><div id="ff'+m+'" class="vi"><div id="i'+m+'"><canvas id="k'+m+'" width="915" height="365"></canvas></div><div id="h'+
m+'" class="as lm ql"><h1 class="iq ij">'+C[m]+"</h1></div></div></div>"}for(b=0;b<p.length;b++)m=b,a+='<a name="'+m+'" id="n'+m+'" class="td" style="right:'+(p.length-m)*20+'px" href=""></a>';a+="</div>";jQuery("#p").html(a);jQuery("#p a");for(b=0;b<p.length;b++)B==1?n[b]=new f.o({name:"k"+b,image:p[b]}):jQuery("#i"+b).html('<img src="'+p[b]+'" />'),jQuery("#f"+b).hide();f.H()}};f.v()}var t;window.addEventListener("e",function(){t!=null&&t.D();
jQuery.fx.off=1;t=null});window.addEventListener("b",function(f){t||f.detail.id!=="intr"||(t=new J)})})();
