/*
 Slider v0.2.0 | (c) 2014 Nerijus Jasinskas */
(function(){function K(){var f=this,v=null,r=0,t=(new Date).getTime()+"-"+Math.floor(Math.random()*1E3+1),B=0;this.j=function(){return t};var p=[],C=!0,D=[],q=[];if(navigator.userAgent.indexOf("MSIE 6")>=0||navigator.userAgent.indexOf("MSIE 7")>=0||navigator.userAgent.indexOf("MSIE 8")>=0)C=!1;this.D=function(){var a=document.getElementById("t");if(a!=null){a=a.getElementsByTagName("a");for(var b=0;b<a.length;++b)D.push(a[b].innerHTML),q.push(a[b].href)}};this.u=function(a){function b(){var k=E[0];
if(!k.h){var l=new Image;k.image=l;k.loaded=!1;l.onload=function(){k.loaded=!0;var e=l.width,h=l.height,m=915/365;var c=h*m;var d=h;c>e&&(c=e,d=e/m);e=(e-c)/2;h=(h-d)/2;c=[e,h,e+c,h+d];d=(c[2]+c[0])/2;h=(c[3]+c[1])/2;e=(c[2]-c[0])*G;m=(c[3]-c[1])*G;d=[d-e/2,h-m/2,d+e/2,h+m/2];e=Math.floor(Math.random()*3)-1;h=Math.floor(Math.random()*3)-1;e/=2;h/=2;m=d[0];d[0]+=m*e;d[2]+=m*e;e=d[1];d[1]+=e*h;d[3]+=e*h;Math.floor(Math.random()*10)%2?(k.r1=c,k.r2=d):(k.r1=d,k.r2=c);if(a.onloaded)a.onloaded(w)};k.h=
!0;l.src=k.path}return k}function n(){var k=(new Date).getTime()-x;var l=k/y;if(!(l>1)){var e=b();if(e.loaded){var h=e.r1;var m=e.r2;var c=h[0];var d=h[1];c+=(m[0]-c)*l;d+=(m[1]-d)*l;var H=h[2],I=h[3];h=H+(m[2]-H)*l;l=I+(m[3]-I)*l;c=[c,d,h,l];z.save();z.globalAlpha=1;z.drawImage(e.image,c[0],c[1],c[2]-c[0],c[3]-c[1],0,0,915,365);z.restore()}}J>0&&F==0&&y-k<=J&&(a.F&&a.F(w,y-k),F=!0);k>=y&&w.stop()}if(!C)return null;var z=jQuery("#"+a.name)[0].getContext("2d"),w=this,x=0,y=a.I||9E3,J=a.J||0,F=!1,L=
1/(a.K||30)*1E3,G=1/(a.zoom||1.5),A=null,E=[];E.push({path:a.image,h:!1,loaded:!1});this.stop=function(){A!=null&&clearInterval(A);A=null;E[0].h=null;if(a.onstop)a.onstop(w)};this.start=function(){F=!1;x=0;x=(new Date).getTime()-x;A=setInterval(n,L)};b();return this};this.g=function(a,b){b==0?jQuery("#n"+a).removeClass("r8"):jQuery("#n"+a).addClass("r8")};this.o=function(){v!=null&&(window.clearTimeout(v),v=null)};this.G=function(){var a=r;a++;a==q.length&&(a=0);return a};this.m=function(){for(var a=
0;a<q.length;a++)jQuery("#f"+a).stop(!0,!0),jQuery("#ff"+a).stop(!0,!0)};this.i=function(){f.o();for(var a=0;a<p.length;a++)p[a].stop();this.m()};this.B=function(){var a=r;r=f.G();f.C(a,r)};this.C=function(a,b){B==1&&f.m();B=1;f.l();p.length>b&&p[b].start();jQuery("#ff"+a).css("z-index",1);jQuery("#ff"+b).css("z-index",2);jQuery("#ff"+b).hide().fadeIn(2500,function(){if(t!=f.j())return!1;jQuery("#f"+a).hide();B=0});f.g(a,0);f.g(b,1);jQuery("#f"+b).show(1,function(){});p.length>a&&p[a].stop()};this.l=
function(){window.g&&f.i();f.o();document.getElementById("p")!=null&&(v=window.setTimeout(function(){f!=null&&f.v(t)},5E3))};this.v=function(a){t==a&&f.B()};this.H=function(){r=0;f.l();p.length&&p[0].start();jQuery("#f"+r).show(1,function(){if(t!=f.j())return!1;f.g(r,1)})};this.A=function(){if(document.getElementById("p")!=null){this.D();for(var a='<div style="position: relative;">',b=0;b<D.length;b++){var n=b;a+='<div id="f'+n+'"><div id="ff'+n+'" class="vi"><div id="i'+n+'"><canvas id="k'+
n+'" width="915" height="365"></canvas></div><div id="h'+n+'" class="as lm ql"><h1 class="iq ij">'+D[n]+"</h1></div></div></div>"}for(b=0;b<q.length;b++)n=b,a+='<a name="'+n+'" id="n'+n+'" class="td" style="right:'+(q.length-n)*20+'px" href=""></a>';a+="</div>";jQuery("#p").html(a);jQuery("#p a");for(b=0;b<q.length;b++)C==1?p[b]=new f.u({name:"k"+b,image:q[b]}):jQuery("#i"+b).html('<img src="'+q[b]+'" />'),jQuery("#f"+b).hide();f.H()}};f.A()}var u;
window.addEventListener("e",function(){u!=null&&u.i();jQuery.fx.off=1;u=null});window.addEventListener("b",function(f){u||f.detail.id!=="intr"||(u=new K)})})();
