/*
 Search v0.2.0 | (c) 2015 Nerijus Jasinskas */
(function(){function A(){function r(b){var e=document.createElement("ul");e.className="profile-node";var d=document.createElement("li");d.className="us";var c=document.createElement("span");c.className="profile-name";c.textContent=b.name||"root";d.appendChild(c);if(b.children&&b.children.length>0){var g=document.createElement("ul");g.className="profile-children";b.children.forEach(function(a){g.appendChild(r(a))});d.appendChild(g)}e.appendChild(d);return e}function m(b){if(window.innerWidth<=
800){var e=document.getElementById("pf");e.innerHTML="";var d=document.createElement("div");d.className="vj";b&&b.children&&b.children.length>0&&(b.children.forEach(function(c){c=r(c);d.appendChild(c)}),e.appendChild(d))}else y(b)}function t(b,e){if(b.children)b.children.forEach(function(c){t(c,e)});else if(b.parent&&b.parent.children){var d=b.parent.children.filter(function(c){return n(c,1,e)||n(c,-1,e)});d.length>0?b.parent.children=d:(b.parent.children=null,t(b.parent,e))}}function n(b,
e,d){if(b){if(b.depth>0&&b.name.toLowerCase().indexOf(d.toLowerCase())>=0||e<0&&n(b.parent,e,d))return!0;var c=b.children;c||(c=b.g);if(e>0&&c)for(b=0;b<c.length;++b)if(n(c[b],e,d))return!0}return!1}function y(b){var e=d3.event&&d3.event.altKey?5E3:500,d=k.nodes(h).reverse();k.size([Math.max(150,Math.min(1950,d.length*11)),u]);d=k.nodes(h).reverse();d=d.filter(function(a){return a.depth!=0});d.forEach(function(a){a.y=a.depth<=2?a.depth*50:a.depth*80});var c=z.selectAll("g.xs").data(d,function(a){return a.id||
(a.id=++B)}),g=c.enter().append("svg:g").attr("class","xs").attr("transform",function(){return"translate("+b.i+","+b.h+")"}).on("click",function(a){a.children?(a.g=a.children,a.children=null):(a.children=a.g,a.g=null);y(a)});g.append("svg:circle").attr("r",1E-6).style("fill",function(a){return a.g?"lightsteelblue":"#fff"});g.append("svg:text").attr("x",function(a){return a.depth<=1?-10:10}).attr("dy",".35em").attr("text-anchor",function(a){return a.depth<=1?"end":"start"}).text(function(a){return a.name}).style("fill-opacity",
1E-6).style("font-weight",function(a){return a.depth<=1?"bold":"normal"});g=c.transition().duration(e).attr("transform",function(a){return"translate("+a.y+","+a.x+")"});g.select("circle").attr("r",4.5).style("fill",function(a){return a.g?"lightsteelblue":"#fff"});g.select("text").style("fill-opacity",1);c=c.exit().transition().duration(e).attr("transform",function(){return"translate("+b.y+","+b.x+")"}).remove();c.select("circle").attr("r",1E-6);c.select("text").style("fill-opacity",1E-6);c=z.selectAll("path.or").data(k.links(d),
function(a){return a.target.id});c.enter().insert("svg:path","g").attr("class","or").attr("d",function(){var a={x:b.h,y:b.i};return p({source:a,target:a})}).transition().duration(e).attr("d",p);c.transition().duration(e).attr("d",p);c.exit().transition().duration(e).attr("d",function(){var a={x:b.x,y:b.y};return p({source:a,target:a})}).remove();d.forEach(function(a){a.h=a.x;a.i=a.y})}jQuery("#fc").show();var q=jQuery("#ff"),v,w="",f=jQuery("#cf");f.off();q.off();f.click(function(){q.val("");q.trigger("keyup")});
f=[20,120,20,120];var u=800-f[1]-f[3],x=2E3-f[0]-f[2],B=0,h,l,k=d3.layout.cluster().size([x,u]),p=d3.svg.diagonal().projection(function(b){return[b.y,b.x]}),z=d3.select("#pf").append("svg:svg").attr("width",u+f[1]+f[3]).attr("height",x+f[0]+f[2]).append("svg:g").attr("transform","translate("+f[3]+","+f[0]+")");d3.json("../de/data/profile.json?v=48",function(b){l=b;l.h=x/2;l.i=0;h=jQuery.extend(!0,[],l);m(h);q.on("input propertychange keyup",function(){v=jQuery(this).val().toLowerCase();w!=v&&(w=v,
h=jQuery.extend(!0,[],l),k.nodes(h),t(h,w),m(h))})})}jQuery(document).on("b",function(r,m){m=="srch"&&A()});jQuery(document).trigger("j",["srch"])})();
